version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './log:/var/log/nginx'
      #- '/etc/letsencrypt:/etc/letsencrypt'
      #- './options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf'
    networks:
      default:
        ipv4_address: 10.253.254.40

networks:
  default:
   external:
     name: php-apache
